### ISSUE TITLE
Raid Frames not getting black reskin

### ISSUE THREAD

**Issue by bukovyn** [Pridity/Lorti-UI-Classic#2]
First of all - thanks for porting this to the TBC client, probably my  no. 1 addon.

Raid frames work as intended but if you toggle the setting to enable party frames as raid frames (group of 5 or less), it is not reskinned. I think this might be using a different variable from what you have listed here https://github.com/Pridity/Lorti-UI-Classic/blob/main/core/frames.lua#L149-L170.

I'd be happy to help with a pull request if this isn't something obvious. Thanks!

![image](https://user-images.githubusercontent.com/19196333/119229889-e957f700-bae7-11eb-8a4f-fddf0e2728bf.png)

**Comment by Sukhumi** [comment]
Happens when you are in party and you have groups together turned on.

**Comment by Pridity** [comment]
Should be fixed thanks to Sukhumi

**Comment by bukovyn** [comment]
thanks 👍🏻
